name: selenium-web-test

on:
  push:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Google Chrome # Using shell script to install Google Chrome
        run: |
            chmod +x ./scripts/InstallChrome.sh
             ./scripts/InstallChrome.sh

      - name: Build and Run Tests with Maven
        run: mvn -B clean verify test

      - name: Copy test execution videos & screenshots
        run: |
          mkdir public
          cp -r target/cucumber-report-html public/reports

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
